# Generated by Django 3.1.5 on 2021-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210201_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.CharField(max_length=255, verbose_name='Текст факта')),
                ('is_active', models.BooleanField(default=False, verbose_name='Выкладывать?')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Факт дня',
                'verbose_name_plural': 'Факты дня',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
