# Generated by Django 3.1.5 on 2021-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210203_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles-photo/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
