# Generated by Django 3.1.5 on 2021-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выводить на экран?'),
        ),
    ]
