# Generated by Django 3.1.5 on 2021-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210203_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
    ]
